# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2768b79a4ea27fdb7bac862ac18a90d5082e63aff70fc7b64a221d283a1e2f2bf72dc406b7b260fbd3c33891246036374776fb5a0790a5c182b8d8e74d7005e0

test:
  secret_key_base: bfdfe15f47a733675a807b6c5a5a38b6e00b9920a117557e450d01ccc74d3a36a11743a9723cd6744bcd5fd92972f8c5d3f808e46f661efa2fe366e2f31a3aa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
